use super::{gen_consonant::Consonants, gen_vowel::Vowels};

pub fn gen_hiragana(consonant: Consonants, vowel: Vowels) -> &'static str {
    match consonant {
        Consonants::K => match vowel {
            Vowels::A => "か",
            Vowels::I => "き",
            Vowels::U => "く",
            Vowels::E => "け",
            Vowels::O => "こ",
            _ => "",
        },
        Consonants::Ky => match vowel {
            Vowels::A => "きゃ",
            Vowels::I => "きぃ",
            Vowels::U => "きゅ",
            Vowels::E => "きぇ",
            Vowels::O => "きょ",
            _ => "",
        },
        Consonants::G => match vowel {
            Vowels::A => "が",
            Vowels::I => "ぎ",
            Vowels::U => "ぐ",
            Vowels::E => "げ",
            Vowels::O => "ご",
            _ => "",
        },
        Consonants::Gy => match vowel {
            Vowels::A => "ぎゃ",
            Vowels::I => "ぎぃ",
            Vowels::U => "ぎゅ",
            Vowels::E => "ぎぇ",
            Vowels::O => "ぎょ",
            _ => "",
        },
        Consonants::S => match vowel {
            Vowels::A => "さ",
            Vowels::I => "し",
            Vowels::U => "す",
            Vowels::E => "せ",
            Vowels::O => "そ",
            _ => "",
        },
        Consonants::Sy => match vowel {
            Vowels::A => "しゃ",
            Vowels::I => "しぃ",
            Vowels::U => "しゅ",
            Vowels::E => "しぇ",
            Vowels::O => "しょ",
            _ => "",
        },
        Consonants::Sh => match vowel {
            Vowels::A => "しゃ",
            Vowels::I => "しぃ",
            Vowels::U => "しゅ",
            Vowels::E => "しぇ",
            Vowels::O => "しょ",
            _ => "",
        },
        Consonants::Sg => match vowel {
            Vowels::A => "しゃ",
            Vowels::I => "しぃ",
            Vowels::U => "しゅ",
            Vowels::E => "しぇ",
            Vowels::O => "しょ",
            _ => "",
        },
        Consonants::Z => match vowel {
            Vowels::A => "ざ",
            Vowels::I => "じ",
            Vowels::U => "ず",
            Vowels::E => "ぜ",
            Vowels::O => "ぞ",
            _ => "",
        },
        Consonants::J => match vowel {
            Vowels::A => "じゃ",
            Vowels::I => "じぃ",
            Vowels::U => "じゅ",
            Vowels::E => "じぇ",
            Vowels::O => "じょ",
            _ => "",
        },
        Consonants::Zy => match vowel {
            Vowels::A => "じゃ",
            Vowels::I => "じぃ",
            Vowels::U => "じゅ",
            Vowels::E => "じぇ",
            Vowels::O => "じょ",
            _ => "",
        },
        Consonants::Zg => match vowel {
            Vowels::A => "じゃ",
            Vowels::I => "じぃ",
            Vowels::U => "じゅ",
            Vowels::E => "じぇ",
            Vowels::O => "じょ",
            _ => "",
        },
        Consonants::T => match vowel {
            Vowels::A => "た",
            Vowels::I => "ち",
            Vowels::U => "つ",
            Vowels::E => "て",
            Vowels::O => "と",
            _ => "",
        },
        Consonants::Ty => match vowel {
            Vowels::A => "ちゃ",
            Vowels::I => "ちぃ",
            Vowels::U => "ちゅ",
            Vowels::E => "ちぇ",
            Vowels::O => "ちょ",
            _ => "",
        },
        Consonants::Th => match vowel {
            Vowels::A => "てゃ",
            Vowels::I => "てぃ",
            Vowels::U => "てゅ",
            Vowels::E => "てぇ",
            Vowels::O => "てょ",
            _ => "",
        },
        Consonants::D => match vowel {
            Vowels::A => "だ",
            Vowels::I => "ぢ",
            Vowels::U => "づ",
            Vowels::E => "で",
            Vowels::O => "ど",
            _ => "",
        },
        Consonants::Dy => match vowel {
            Vowels::A => "ぢゃ",
            Vowels::I => "ぢぃ",
            Vowels::U => "ぢゅ",
            Vowels::E => "ぢぇ",
            Vowels::O => "ぢょ",
            _ => "",
        },
        Consonants::Dh => match vowel {
            Vowels::A => "でゃ",
            Vowels::I => "でぃ",
            Vowels::U => "でゅ",
            Vowels::E => "でぇ",
            Vowels::O => "でょ",
            _ => "",
        },
        Consonants::N => match vowel {
            Vowels::A => "な",
            Vowels::I => "に",
            Vowels::U => "ぬ",
            Vowels::E => "ね",
            Vowels::O => "の",
            _ => "",
        },
        Consonants::Ny => match vowel {
            Vowels::A => "にゃ",
            Vowels::I => "にぃ",
            Vowels::U => "にゅ",
            Vowels::E => "にぇ",
            Vowels::O => "にょ",
            _ => "",
        },
        Consonants::H => match vowel {
            Vowels::A => "は",
            Vowels::I => "ひ",
            Vowels::U => "ふ",
            Vowels::E => "へ",
            Vowels::O => "ほ",
            _ => "",
        },
        Consonants::Hy => match vowel {
            Vowels::A => "ひゃ",
            Vowels::I => "ひぃ",
            Vowels::U => "ひゅ",
            Vowels::E => "ひぇ",
            Vowels::O => "ひょ",
            _ => "",
        },
        Consonants::Hg => match vowel {
            Vowels::A => "ひゃ",
            Vowels::I => "ひぃ",
            Vowels::U => "ひゅ",
            Vowels::E => "ひぇ",
            Vowels::O => "ひょ",
            _ => "",
        },
        Consonants::F => match vowel {
            Vowels::A => "ふぁ",
            Vowels::I => "ふぃ",
            Vowels::U => "ふ",
            Vowels::E => "ふぇ",
            Vowels::O => "ふぉ",
            _ => "",
        },
        Consonants::Fy => match vowel {
            Vowels::A => "ふゃ",
            Vowels::I => "ふぃ",
            Vowels::U => "ふゅ",
            Vowels::E => "ふぇ",
            Vowels::O => "ふょ",
            _ => "",
        },
        Consonants::B => match vowel {
            Vowels::A => "ば",
            Vowels::I => "び",
            Vowels::U => "ぶ",
            Vowels::E => "べ",
            Vowels::O => "ぼ",
            _ => "",
        },
        Consonants::By => match vowel {
            Vowels::A => "びゃ",
            Vowels::I => "びぃ",
            Vowels::U => "びゅ",
            Vowels::E => "びぇ",
            Vowels::O => "びょ",
            _ => "",
        },
        Consonants::Bg => match vowel {
            Vowels::A => "びゃ",
            Vowels::I => "びぃ",
            Vowels::U => "びゅ",
            Vowels::E => "びぇ",
            Vowels::O => "びょ",
            _ => "",
        },
        Consonants::P => match vowel {
            Vowels::A => "ぱ",
            Vowels::I => "ぴ",
            Vowels::U => "ぷ",
            Vowels::E => "ぺ",
            Vowels::O => "ぽ",
            _ => "",
        },
        Consonants::Py => match vowel {
            Vowels::A => "ぴゃ",
            Vowels::I => "ぴぃ",
            Vowels::U => "ぴゅ",
            Vowels::E => "ぴぇ",
            Vowels::O => "ぴょ",
            _ => "",
        },
        Consonants::Pg => match vowel {
            Vowels::A => "ぴゃ",
            Vowels::I => "ぴぃ",
            Vowels::U => "ぴゅ",
            Vowels::E => "ぴぇ",
            Vowels::O => "ぴょ",
            _ => "",
        },
        Consonants::M => match vowel {
            Vowels::A => "ま",
            Vowels::I => "み",
            Vowels::U => "む",
            Vowels::E => "め",
            Vowels::O => "も",
            _ => "",
        },
        Consonants::My => match vowel {
            Vowels::A => "みゃ",
            Vowels::I => "みぃ",
            Vowels::U => "みゅ",
            Vowels::E => "みぇ",
            Vowels::O => "みょ",
            _ => "",
        },
        Consonants::Y => match vowel {
            Vowels::A => "や",
            Vowels::I => "い",
            Vowels::U => "ゆ",
            Vowels::E => "いぇ",
            Vowels::O => "よ",
            _ => "",
        },
        Consonants::R => match vowel {
            Vowels::A => "ら",
            Vowels::I => "り",
            Vowels::U => "る",
            Vowels::E => "れ",
            Vowels::O => "ろ",
            _ => "",
        },
        Consonants::Ry => match vowel {
            Vowels::A => "りゃ",
            Vowels::I => "りぃ",
            Vowels::U => "りゅ",
            Vowels::E => "りぇ",
            Vowels::O => "りょ",
            _ => "",
        },
        Consonants::W => match vowel {
            Vowels::A => "わ",
            Vowels::I => "うぃ",
            Vowels::U => "う",
            Vowels::E => "うぇ",
            Vowels::O => "を",
            _ => "",
        },
        Consonants::Wh => match vowel {
            Vowels::A => "うぁ",
            Vowels::I => "うぃ",
            Vowels::U => "う",
            Vowels::E => "うぇ",
            Vowels::O => "うぉ",
            _ => "",
        },
        Consonants::V => match vowel {
            Vowels::A => "ゔぁ",
            Vowels::I => "ゔぃ",
            Vowels::U => "ゔ",
            Vowels::E => "ゔぇ",
            Vowels::O => "ゔぉ",
            _ => "",
        },
    }
}

pub fn gen_katakana(consonant: Consonants, vowel: Vowels) -> &'static str {
    match consonant {
        Consonants::K => match vowel {
            Vowels::A => "カ",
            Vowels::I => "キ",
            Vowels::U => "ク",
            Vowels::E => "ケ",
            Vowels::O => "コ",
            _ => "",
        },
        Consonants::Ky => match vowel {
            Vowels::A => "キャ",
            Vowels::I => "キィ",
            Vowels::U => "キュ",
            Vowels::E => "キェ",
            Vowels::O => "キョ",
            _ => "",
        },
        Consonants::G => match vowel {
            Vowels::A => "ガ",
            Vowels::I => "ギ",
            Vowels::U => "グ",
            Vowels::E => "ゲ",
            Vowels::O => "ゴ",
            _ => "",
        },
        Consonants::Gy => match vowel {
            Vowels::A => "ギャ",
            Vowels::I => "ギィ",
            Vowels::U => "ギュ",
            Vowels::E => "ギェ",
            Vowels::O => "ギョ",
            _ => "",
        },
        Consonants::S => match vowel {
            Vowels::A => "サ",
            Vowels::I => "シ",
            Vowels::U => "ス",
            Vowels::E => "セ",
            Vowels::O => "ソ",
            _ => "",
        },
        Consonants::Sy => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Sh => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Sg => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Z => match vowel {
            Vowels::A => "ザ",
            Vowels::I => "ジ",
            Vowels::U => "ズ",
            Vowels::E => "ゼ",
            Vowels::O => "ゾ",
            _ => "",
        },
        Consonants::J => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::Zy => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジィ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::Zg => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジィ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::T => match vowel {
            Vowels::A => "タ",
            Vowels::I => "チ",
            Vowels::U => "ツ",
            Vowels::E => "テ",
            Vowels::O => "ト",
            _ => "",
        },
        Consonants::Ty => match vowel {
            Vowels::A => "チャ",
            Vowels::I => "チィ",
            Vowels::U => "チュ",
            Vowels::E => "チェ",
            Vowels::O => "チョ",
            _ => "",
        },
        Consonants::Th => match vowel {
            Vowels::A => "テャ",
            Vowels::I => "ティ",
            Vowels::U => "テュ",
            Vowels::E => "テェ",
            Vowels::O => "テョ",
            _ => "",
        },
        Consonants::D => match vowel {
            Vowels::A => "ダ",
            Vowels::I => "ヂ",
            Vowels::U => "ヅ",
            Vowels::E => "デ",
            Vowels::O => "ド",
            _ => "",
        },
        Consonants::Dy => match vowel {
            Vowels::A => "ヂャ",
            Vowels::I => "ヂィ",
            Vowels::U => "ヂュ",
            Vowels::E => "ヂェ",
            Vowels::O => "ヂョ",
            _ => "",
        },
        Consonants::Dh => match vowel {
            Vowels::A => "デャ",
            Vowels::I => "ディ",
            Vowels::U => "デュ",
            Vowels::E => "デェ",
            Vowels::O => "デョ",
            _ => "",
        },
        Consonants::N => match vowel {
            Vowels::A => "ナ",
            Vowels::I => "ニ",
            Vowels::U => "ヌ",
            Vowels::E => "ネ",
            Vowels::O => "ノ",
            _ => "",
        },
        Consonants::Ny => match vowel {
            Vowels::A => "ニャ",
            Vowels::I => "ニィ",
            Vowels::U => "ニュ",
            Vowels::E => "ニェ",
            Vowels::O => "ニョ",
            _ => "",
        },
        Consonants::H => match vowel {
            Vowels::A => "ハ",
            Vowels::I => "ヒ",
            Vowels::U => "フ",
            Vowels::E => "ヘ",
            Vowels::O => "ホ",
            _ => "",
        },
        Consonants::Hy => match vowel {
            Vowels::A => "ヒャ",
            Vowels::I => "ヒィ",
            Vowels::U => "ヒュ",
            Vowels::E => "ヒェ",
            Vowels::O => "ヒョ",
            _ => "",
        },
        Consonants::Hg => match vowel {
            Vowels::A => "ヒャ",
            Vowels::I => "ヒィ",
            Vowels::U => "ヒュ",
            Vowels::E => "ヒェ",
            Vowels::O => "ヒョ",
            _ => "",
        },
        Consonants::F => match vowel {
            Vowels::A => "ファ",
            Vowels::I => "フィ",
            Vowels::U => "フ",
            Vowels::E => "フェ",
            Vowels::O => "フォ",
            _ => "",
        },
        Consonants::Fy => match vowel {
            Vowels::A => "フャ",
            Vowels::I => "フィ",
            Vowels::U => "フュ",
            Vowels::E => "フェ",
            Vowels::O => "フョ",
            _ => "",
        },
        Consonants::B => match vowel {
            Vowels::A => "バ",
            Vowels::I => "ビ",
            Vowels::U => "ブ",
            Vowels::E => "ベ",
            Vowels::O => "ボ",
            _ => "",
        },
        Consonants::By => match vowel {
            Vowels::A => "ビャ",
            Vowels::I => "ビィ",
            Vowels::U => "ビュ",
            Vowels::E => "ビェ",
            Vowels::O => "ビョ",
            _ => "",
        },
        Consonants::Bg => match vowel {
            Vowels::A => "ビャ",
            Vowels::I => "ビィ",
            Vowels::U => "ビュ",
            Vowels::E => "ビェ",
            Vowels::O => "ビョ",
            _ => "",
        },
        Consonants::P => match vowel {
            Vowels::A => "パ",
            Vowels::I => "ピ",
            Vowels::U => "プ",
            Vowels::E => "ペ",
            Vowels::O => "ポ",
            _ => "",
        },
        Consonants::Py => match vowel {
            Vowels::A => "ピャ",
            Vowels::I => "ピィ",
            Vowels::U => "ピュ",
            Vowels::E => "ピェ",
            Vowels::O => "ピョ",
            _ => "",
        },
        Consonants::Pg => match vowel {
            Vowels::A => "ピャ",
            Vowels::I => "ピィ",
            Vowels::U => "ピュ",
            Vowels::E => "ピェ",
            Vowels::O => "ピョ",
            _ => "",
        },
        Consonants::M => match vowel {
            Vowels::A => "マ",
            Vowels::I => "ミ",
            Vowels::U => "ム",
            Vowels::E => "メ",
            Vowels::O => "モ",
            _ => "",
        },
        Consonants::My => match vowel {
            Vowels::A => "ミャ",
            Vowels::I => "ミィ",
            Vowels::U => "ミュ",
            Vowels::E => "ミェ",
            Vowels::O => "ミョ",
            _ => "",
        },
        Consonants::Y => match vowel {
            Vowels::A => "ヤ",
            Vowels::I => "イ",
            Vowels::U => "ユ",
            Vowels::E => "イェ",
            Vowels::O => "ヨ",
            _ => "",
        },
        Consonants::R => match vowel {
            Vowels::A => "ラ",
            Vowels::I => "リ",
            Vowels::U => "ル",
            Vowels::E => "レ",
            Vowels::O => "ロ",
            _ => "",
        },
        Consonants::Ry => match vowel {
            Vowels::A => "リャ",
            Vowels::I => "リィ",
            Vowels::U => "リュ",
            Vowels::E => "リェ",
            Vowels::O => "リョ",
            _ => "",
        },
        Consonants::W => match vowel {
            Vowels::A => "ワ",
            Vowels::I => "ウィ",
            Vowels::U => "ウ",
            Vowels::E => "ウェ",
            Vowels::O => "ヲ",
            _ => "",
        },
        Consonants::Wh => match vowel {
            Vowels::A => "ウア",
            Vowels::I => "ウィ",
            Vowels::U => "ウ",
            Vowels::E => "ウェ",
            Vowels::O => "ウォ",
            _ => "",
        },
        Consonants::V => match vowel {
            Vowels::A => "ヴァ",
            Vowels::I => "ヴィ",
            Vowels::U => "ヴ",
            Vowels::E => "ヴェ",
            Vowels::O => "ヴォ",
            _ => "",
        },
    }
}

pub fn gen_half_katakana(consonant: Consonants, vowel: Vowels) -> &'static str {
    match consonant {
        Consonants::K => match vowel {
            Vowels::A => "ｶ",
            Vowels::I => "ｷ",
            Vowels::U => "ｸ",
            Vowels::E => "ｹ",
            Vowels::O => "ｺ",
            _ => "",
        },
        Consonants::Ky => match vowel {
            Vowels::A => "ｷｬ",
            Vowels::I => "ｷｨ",
            Vowels::U => "ｷｭ",
            Vowels::E => "ｷｪ",
            Vowels::O => "ｷｮ",
            _ => "",
        },
        Consonants::G => match vowel {
            Vowels::A => "ｶﾞ",
            Vowels::I => "ｷﾞ",
            Vowels::U => "ｸﾞ",
            Vowels::E => "ｹﾞ",
            Vowels::O => "ｺﾞ",
            _ => "",
        },
        Consonants::Gy => match vowel {
            Vowels::A => "ｷﾞｬ",
            Vowels::I => "ｷﾞｨ",
            Vowels::U => "ｷﾞｭ",
            Vowels::E => "ｷﾞｪ",
            Vowels::O => "ｷﾞｮ",
            _ => "",
        },
        Consonants::S => match vowel {
            Vowels::A => "ｻ",
            Vowels::I => "ｼ",
            Vowels::U => "ｽ",
            Vowels::E => "ｾ",
            Vowels::O => "ｿ",
            _ => "",
        },
        Consonants::Sy => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Sh => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Sg => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Z => match vowel {
            Vowels::A => "ｻﾞ",
            Vowels::I => "ｼﾞ",
            Vowels::U => "ｽﾞ",
            Vowels::E => "ｾﾞ",
            Vowels::O => "ｿﾞ",
            _ => "",
        },
        Consonants::J => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::Zy => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞｨ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::Zg => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞｨ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::T => match vowel {
            Vowels::A => "ﾀﾀ",
            Vowels::I => "ﾁ",
            Vowels::U => "ﾂ",
            Vowels::E => "ﾃ",
            Vowels::O => "ﾄ",
            _ => "",
        },
        Consonants::Ty => match vowel {
            Vowels::A => "ﾁｬ",
            Vowels::I => "ﾁｨ",
            Vowels::U => "ﾁｭ",
            Vowels::E => "ﾁｪ",
            Vowels::O => "ﾁｮ",
            _ => "",
        },
        Consonants::Th => match vowel {
            Vowels::A => "ﾃｬ",
            Vowels::I => "ﾃｨ",
            Vowels::U => "ﾃｭ",
            Vowels::E => "ﾃｪ",
            Vowels::O => "ﾃﾖ",
            _ => "",
        },
        Consonants::D => match vowel {
            Vowels::A => "ﾀﾞ",
            Vowels::I => "ﾁﾞ",
            Vowels::U => "ﾂﾞ",
            Vowels::E => "ﾃﾞ",
            Vowels::O => "ﾄﾞ",
            _ => "",
        },
        Consonants::Dy => match vowel {
            Vowels::A => "ﾁﾞｬ",
            Vowels::I => "ﾁﾞｨ",
            Vowels::U => "ﾁﾞｭ",
            Vowels::E => "ﾁﾞｪ",
            Vowels::O => "ﾁﾞｮ",
            _ => "",
        },
        Consonants::Dh => match vowel {
            Vowels::A => "ﾃﾞｬ",
            Vowels::I => "ﾃﾞｨ",
            Vowels::U => "ﾃﾞｭ",
            Vowels::E => "ﾃﾞｪ",
            Vowels::O => "ﾃﾞｮ",
            _ => "",
        },
        Consonants::N => match vowel {
            Vowels::A => "ﾅ",
            Vowels::I => "ﾆ",
            Vowels::U => "ﾇ",
            Vowels::E => "ﾈ",
            Vowels::O => "ﾉ",
            _ => "",
        },
        Consonants::Ny => match vowel {
            Vowels::A => "ﾆｬ",
            Vowels::I => "ﾆｨ",
            Vowels::U => "ﾆｭ",
            Vowels::E => "ﾆｪ",
            Vowels::O => "ﾆｮ",
            _ => "",
        },
        Consonants::H => match vowel {
            Vowels::A => "ﾊ",
            Vowels::I => "ﾋ",
            Vowels::U => "ﾌ",
            Vowels::E => "ﾍ",
            Vowels::O => "ﾎ",
            _ => "",
        },
        Consonants::Hy => match vowel {
            Vowels::A => "ﾋｬ",
            Vowels::I => "ﾋｨ",
            Vowels::U => "ﾋｭ",
            Vowels::E => "ﾋｪ",
            Vowels::O => "ﾋｮ",
            _ => "",
        },
        Consonants::Hg => match vowel {
            Vowels::A => "ﾋｬ",
            Vowels::I => "ﾋｨ",
            Vowels::U => "ﾋｭ",
            Vowels::E => "ﾋｪ",
            Vowels::O => "ﾋｮ",
            _ => "",
        },
        Consonants::F => match vowel {
            Vowels::A => "ﾌｧ",
            Vowels::I => "ﾌｨ",
            Vowels::U => "ﾌ",
            Vowels::E => "ﾌｪ",
            Vowels::O => "ﾌｫ",
            _ => "",
        },
        Consonants::Fy => match vowel {
            Vowels::A => "ﾌｬ",
            Vowels::I => "ﾌｨ",
            Vowels::U => "ﾌﾕ",
            Vowels::E => "ﾌｪ",
            Vowels::O => "ﾌｮ",
            _ => "",
        },
        Consonants::B => match vowel {
            Vowels::A => "ﾊﾞ",
            Vowels::I => "ﾋﾞ",
            Vowels::U => "ﾌﾞ",
            Vowels::E => "ﾍﾞ",
            Vowels::O => "ﾎﾞ",
            _ => "",
        },
        Consonants::By => match vowel {
            Vowels::A => "ﾋﾞｬ",
            Vowels::I => "ﾋﾞｨ",
            Vowels::U => "ﾋﾞｭ",
            Vowels::E => "ﾋﾞｪ",
            Vowels::O => "ﾋﾞｮ",
            _ => "",
        },
        Consonants::Bg => match vowel {
            Vowels::A => "ﾋﾞｬ",
            Vowels::I => "ﾋﾞｨ",
            Vowels::U => "ﾋﾞｭ",
            Vowels::E => "ﾋﾞｪ",
            Vowels::O => "ﾋﾞｮ",
            _ => "",
        },
        Consonants::P => match vowel {
            Vowels::A => "ﾊﾟ",
            Vowels::I => "ﾋﾟ",
            Vowels::U => "ﾌﾟ",
            Vowels::E => "ﾍﾟ",
            Vowels::O => "ﾎﾟ",
            _ => "",
        },
        Consonants::Py => match vowel {
            Vowels::A => "ﾋﾟｬ",
            Vowels::I => "ﾋﾟｨ",
            Vowels::U => "ﾋﾟｭ",
            Vowels::E => "ﾋﾟｪ",
            Vowels::O => "ﾋﾟｮ",
            _ => "",
        },
        Consonants::Pg => match vowel {
            Vowels::A => "ﾋﾟｬ",
            Vowels::I => "ﾋﾟｨ",
            Vowels::U => "ﾋﾟｭ",
            Vowels::E => "ﾋﾟｪ",
            Vowels::O => "ﾋﾟｮ",
            _ => "",
        },
        Consonants::M => match vowel {
            Vowels::A => "ﾏ",
            Vowels::I => "ﾐ",
            Vowels::U => "ﾑ",
            Vowels::E => "ﾒ",
            Vowels::O => "ﾓ",
            _ => "",
        },
        Consonants::My => match vowel {
            Vowels::A => "ﾐｬ",
            Vowels::I => "ﾐｨ",
            Vowels::U => "ﾐｭ",
            Vowels::E => "ﾐｪ",
            Vowels::O => "ﾐｮ ",
            _ => "",
        },
        Consonants::Y => match vowel {
            Vowels::A => "ﾔ",
            Vowels::I => "ｲ",
            Vowels::U => "ﾕ",
            Vowels::E => "ｲｪ",
            Vowels::O => "ﾖ",
            _ => "",
        },
        Consonants::R => match vowel {
            Vowels::A => "ﾗ",
            Vowels::I => "ﾘ",
            Vowels::U => "ﾙ",
            Vowels::E => "ﾚ",
            Vowels::O => "ﾛ",
            _ => "",
        },
        Consonants::Ry => match vowel {
            Vowels::A => "ﾘｬ",
            Vowels::I => "ﾘｨ",
            Vowels::U => "ﾘｭ",
            Vowels::E => "ﾘｪ",
            Vowels::O => "ﾘｮ",
            _ => "",
        },
        Consonants::W => match vowel {
            Vowels::A => "ﾜ",
            Vowels::I => "ｳｨ",
            Vowels::U => "ｳ",
            Vowels::E => "ｳｪ",
            Vowels::O => "ｦ",
            _ => "",
        },
        Consonants::Wh => match vowel {
            Vowels::A => "ｳｧ",
            Vowels::I => "ｳｨ",
            Vowels::U => "ｳ",
            Vowels::E => "ｳｪ",
            Vowels::O => "ｳｫ",
            _ => "",
        },
        Consonants::V => match vowel {
            Vowels::A => "ｳﾞｧ",
            Vowels::I => "ｳﾞｨ",
            Vowels::U => "ｳﾞ",
            Vowels::E => "ｳﾞｪ",
            Vowels::O => "ｳﾞｫ",
            _ => "",
        },
    }
}
